Misc updates
optiqs/projections pull request #4
Opened 2021-03-11 04:36 UTC by josh-degraw

This PR attempts to 

- Improve type declarations
- Deprecate functions that can be removed soon
- Improve the build steps

2021-03-11 18:00 UTC, MCluck90 requested changes

2021-03-11 18:00 UTC, MCluck90 commented on src/projection.ts
> +     */
I don't know that we need to deprecate these. I personally like that you can do `Projection.from` or `Lens.asProjection`

2021-03-11 23:29 UTC, josh-degraw commented on tsconfig.json
> -    "emitDeclarationOnly": true,
I wasn't seeing any js files being built, I only saw the declarations. But if they're working where it matters, I'm sure that's fine.

2021-03-12 17:05 UTC, josh-degraw commented on src/projection.ts
> +     */
Fair enough. I guess I've gotten kind of myopic and was just wanting to remove the side effects lol but yeah we don't need to deprecate these

2021-03-12 17:36 UTC, MCluck90 approved these changes

2021-03-12 17:36 UTC, merged